### ISSUE TITLE
【英】NB_g7-g9_製作論点（TGT・コンテンツ詳細）の入力完了

### ISSUE THREAD

**Issue by mikuri-tanaka** [quipper/g7-9-nb-content-issues#15]
## 目的
英語で、TGTイメージ・コンテンツイメージをそろえるため。

## 何をもってDoneとするか
英語内で目線がそろい、記入内容について同意できていること（保留事項があってもよいが、保留であること、何をまてば決定できるかは同意ができていること）

## 背景
英語メンバー内でイメージをそろえるため。
そろったのちは5教科でイメージをそろえることにつなげる。
※サンプル作成・更新と並行して更新していくこと

## スケジュール
2019/12/26　田中以外が入力内容を確認・加筆
2019/12/27　英語内で目線合わせ→英語内仮FIX＠会議

## 責任者
田中未来里

**Comment by michikoa** [comment]
@mikuri-tanaka 
責任者がみくりさんの場合は、Asigneeをみくりさんにして、issue内で他の人をメンションします。（コンテンツチームの独自ルールですが、このissueのたまもちを明確にするためです）

**Comment by shujiogiri** [comment]
@takuto-kawai @yasuhiro-fujise @nozomikajimoto 
メンションこんな感じで

**Comment by mikuri-tanaka** [comment]
@michikoa @shujiogiri 
なるほどです。ラベルをつけるようなやり方ではなく、ここのコメント欄にメンション先を書くのですね！ありがとうございます！

**Comment by mikuri-tanaka** [comment]
@takuto-kawai  @yasuhiro-fujise @michiyo-shiraishi 
こちらの件、入力内容の確認お願いします！メンションうまくできずすみません！（一応スラックで確認依頼した件です）

**Comment by takuto-kawai** [comment]
こちら先日確認しております！宜しくお願いいたします。

**Comment by michikoa** [comment]
@mikuri-tanaka マイルストーンの更新お願いします！
