### ISSUE TITLE
6教科書の文法単元の切り分け

### ISSUE THREAD

**Issue by yasuhiro-fujise** [quipper/g7-9-nb-content-issues#20]
## 目的
6教科書の文法単元の章立て洗い出し
各教科書の文法単元を統一して共通化する

## 何をもってDoneとするか
6教科書に対応して切り出すことができるような文法単元リスト作成

## 背景
編プロ以来の際，作問の分量の把握をしたい

## スケジュール
19/12/26
※改定教科書でないとモジュール群が正しく切り分けられるかはわからない

## 責任者
藤瀬

**Comment by yasuhiro-fujise** [comment]
#14と目的が異なるので分離，
26中に要るらしいんで

**Comment by yasuhiro-fujise** [comment]
https://docs.google.com/spreadsheets/d/16VJkqVKr9yc_FgnJbizMqO0J9ZvFwqYDSF1C9aQSBTE/edit#gid=1161888158
こちら参照

**Comment by michikoa** [comment]
@yasuhiro-fujise マイルストーンの更新お願いします！

**Comment by yasuhiro-fujise** [comment]
編プロさんに新規作問依頼の場合の単元切り分けはほぼこれで確定のため
doneとします
