### ISSUE TITLE
NB社会_自由社・育鵬社・学び舎の教科書入手の判断

### ISSUE THREAD

**Issue by yukihiro-yoshida** [quipper/g7-9-nb-content-issues#27]
## 目的
自由社・育鵬社・学び舎（教著協管轄外）の3社の教科書を入手するか検討する

（以下宮下さんからの相談）
【社会】
社会の教科書に関しまして、「社会科発行者の自由社・育鵬社、学び舎」の三社は教科書著作権協会の管轄外だそうです。入手のルートが確かではないのですが、絶対必要！とのことでしたら、私から直接各教科書会社にアプローチだけはしてみようと思います。教科書入手の希望度合い教えていただければと思いますので来月中くらいまでに検討いただけないでしょうか。（対照表を必ず作る！とかだったら交渉できると思います）

_Originally posted by @mizuha-miyashita in https://github.com/quipper/g7-9-nb-content-issues/issues/1#issuecomment-567297676_

## 何をもってDoneとするか
- [ ] @mizuha-miyashita に教科書入手の希望度合いを伝える

## 背景
・社会の定期試験は，作成する先生が以前の問題を流用して作ることが多い
→教科書による解法の違いがないため，以前の勤務先採択教科書の表記がママ流用されることがある
・NB社会は標準版での制作だが，使用語句や表現（言い回し），採用資料についてはMECEとなるように設計をしたい
・教科書違いによってターゲットが絞り込まれるリスクを減らす
・とはいえシェア率が低い教科書を考慮するか？を検討する必要がある（採択未定の段階なので，シェア率変動も考慮必要）
・プロダクト作る側が「見たこともない」というのはそもそもどうなのかという…

## スケジュール
- [ ]　3社のシェア確認(現行）（〜2020/01/10）
- [ ]　入手判断（希望度合い）（〜2020/01/10）　

## 責任者
@yukihiro-yoshida

**Comment by yukihiro-yoshida** [comment]
@mizuha-miyashita 
公立中学校採択（シェア）
育鵬社　6.2%
自由社　0.0%
学び舎　0.0%（国立のみ5校採択）

→育鵬社のみ入手・対応が必要と考えています。

**Comment by mizuha-miyashita** [comment]
@yukihiro-yoshida 対照表を作る等、先方に支払いが発生するようなことはありそうかどうかもあわせてご確認をお願いいたします。

**Comment by yukihiro-yoshida** [comment]
@mizuha-miyashita 
（先ほどの立ち話まとめ）

- 対照表を作る必要があります（app内で紐付けをする予定）
- 本文表現を用いる・図版（教科書掲載のものをママ使う，トレースして使う）が発生すると支払い発生する
-- →原則使用しない予定ですが，発生したら出来上がった後に一覧表を作って提出する必要あり
- 写真等の権利関係等，法務的な部分は宮下さんではなく都度法務・先方と検討する必要があるかも
-- →宮下さんには窓口として立っていただくイメージ

認識が違っていたらご指摘ください！
