### ISSUE TITLE
NB数学_学校ワーク収集・選定

### ISSUE THREAD

**Issue by tomoya-endo640** [quipper/g7-9-nb-content-issues#3]
## 目的
- 単元表、問題選定のベンチマークとする学校ワークを決定する
- そのために、可能な限り収集＋分析

## 何をもってDoneとするか
- 最終的にいけてる学校ワーク決定
　→構想表を作成開始できる状態にする

## スケジュール
- @hiroki-tomita916 さんが収集　←　Done
- ~12/19までに分析＋決定
- 記録は次に蓄積　→　[学校ワーク分析（集計）](https://docs.google.com/spreadsheets/d/1mwdx4zJA0CcTHPYYYe4m8Y9xNMMSxdUfKNcu2t7BQ4Q/edit?folder=1ipi6aGJvajgHL10saQWgzJ2rzlvp9obC#gid=0)

## 責任者
@tomoya-endo640

**Comment by tomoya-endo640** [comment]
@hiroki-tomita916 
収集した学校ワーク、以下にタイトルだけ書いてもらってもよいですか？
①分析観点を決定
②分析
③ワーク決定
の流れでいきます。（今のところ正進社＋東書の予定ですが、念のため）
https://docs.google.com/document/d/1mAA61eX1AFgGmaPcijzdgTjWvS13rxwPEBbi4MdiSZo/edit

**Comment by michikoa** [comment]
@tomoya-endo640 issueありがとうございます。Asigneeだけどちらかお一人にしていただければと思います！

**Comment by tomoya-endo640** [comment]
@michikoa 
OKです、変更しました！

**Comment by tomoya-endo640** [comment]
12/18
- 7種類の分析完了
- 何を基準にベンチマークにするワークを選定するか、明日のmtgで決定

**Comment by tomoya-endo640** [comment]
12/19
数学のmtgより抜粋
- 問題全体：正進社「数学の学習ノート(東)」
- 解答全体：明治図書
- 途中式　：東書の「基礎からの問題集」

**Comment by tomoya-endo640** [comment]
12/23
- いったんベンチマーク（参考+利用）とするワークを決定したので、Done
　⇒以降、どのように使用するか決定した際に、改めて追加記載
