### ISSUE TITLE
NB社会_学校ワーク購入

### ISSUE THREAD

**Issue by yukihiro-yoshida** [quipper/g7-9-nb-content-issues#6]
## 背景
NBの方針として「学校ワークの学習をしやすくする」を置いている
ベンチマークとなる学校ワークを探す
学校ワークごとのページ構成・問題構成の分析→new productに反映する

## 対応策
以下のリストのものを購入
https://docs.google.com/spreadsheets/d/1ALnc9xmd7QAaDjgJUZQYi1qDrS7GRUk49FkdtJ3oh0g/edit#gid=1114752073
購入方法はメルカリ，ヤフオク
個人のクレジットカードで購入→建て替え精算

## スケジュール
[済]12/12（木）メルカリ・ヤフオクで購入
12/16（月）〜　不足分を適宜購入

**Comment by michikoa** [comment]
@yukihiro-yoshida 　
Asigneeだけどちらかお一人にしていただければと思います！milestone仮置きしました。

**Comment by yukihiro-yoshida** [comment]
@michikoa 
修正しました！

**Comment by yukihiro-yoshida** [comment]
オレンジ色のものが発注・購入したもの
![image](https://user-images.githubusercontent.com/48504121/71221785-3ba05180-2311-11ea-8c7e-7be63a096159.png)

**Comment by yukihiro-yoshida** [comment]
@masashi-arai725 
こちら頼んだものが全て届いているか，チェックしていただけますか？
12/23（月）までにわかっているとありがたいです！

**Comment by masashi-arai725** [comment]
@yukihiro-yoshida 
承知しました！

**Comment by yukihiro-yoshida** [comment]
@masashi-arai725 
チェック状況をこちらに貼っていただけると！（URLでも画像でもOK）

**Comment by masashi-arai725** [comment]
@yukihiro-yoshida 
E列に到着状況✔つけています。吉田さんが頼まれたものは全て到着済。新井が頼んだものが10冊未着です！
https://docs.google.com/spreadsheets/d/1ALnc9xmd7QAaDjgJUZQYi1qDrS7GRUk49FkdtJ3oh0g/edit?pli=1#gid=1114752073

**Comment by masashi-arai725** [comment]
@yukihiro-yoshida 
購入分全部届きました！
